dataset: BioSNAP
cv_mode: CVS1
data_dir: data/BioSNAP
ligand_embed: data/BioSNAP/ligand_embeddings.csv
target_embed: data/BioSNAP/protein_embeddings.csv
checkpoint_dir: checkpoints/BioSNAP/CVS1_MCG-HGT
num_epochs: 250
k_fold: 10
batch_size: 4096
lr: 0.0001
wd: 0.00001
graph_struct: 3
method: 5
in_dim: 512
h_dim: 1024
out_dim: 512
hgt_heads: 8
num_layers: 3
fanout: 15
neg_k: 5
input_gate_type: glu
score_gate: gmu
semantic_gate: etype
residual_gate: true
head_gate: true
dropout: 0.2
monitor_metric: auprc
